const state = {
  cards: [
    {
      imgSrc: './assets/yoda.jpeg',
      productName: 'Yoda',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 900,
      amountOfViews: 45333,
    },
    {
      imgSrc: './assets/wolf.jpg',
      productName: 'Wolf',
      productInfo: 'New, Addidas',
      productCategory: 'Toy, kids',
      amountOfLikes: 456,
      amountOfViews: 232323,
    },
    {
      imgSrc: './assets/han.jpg',
      productName: 'Han Solo',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 123,
      amountOfViews: 553434,
    },
    {
      imgSrc: './assets/panda.jpg',
      productName: 'Panda',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 987,
      amountOfViews: 5653,
    },
    {
      imgSrc: './assets/zebra.jpg',
      productName: 'Zebra',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 12,
      amountOfViews: 5435,
    },
    {
      imgSrc: './assets/puma.jpg',
      productName: 'Puma',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 2,
      amountOfViews: 4,
    },
    {
      imgSrc: './assets/snake.jpg',
      productName: 'Snake',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 55,
      amountOfViews: 7898,
    },
    {
      imgSrc: './assets/tiger.jpg',
      productName: 'Tiger',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 333,
      amountOfViews: 45333,
    },
    {
      imgSrc: './assets/panter.jpg',
      productName: 'Panter',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 545,
      amountOfViews: 65656,
    },
    {
      imgSrc: './assets/yoda.jpeg',
      productName: 'Yoda',
      productInfo: 'New, Nike',
      productCategory: 'Toy, kids',
      amountOfLikes: 343433,
      amountOfViews: 656565656,
    },
  ],
};

export default state;
